function [grid, run, constants, flow, bconds] =  build_structs()

    grid = struct('nx', [], 'ny', [], ...
                  'x', [], 'y', [], ...
                  'dx',[], 'dy', [], ...
                  'xmin', [], 'xmax', [], ...
                  'ymin', [], 'ymax', [], ... 
                  'NGHOST', [] ...                
                  );
             
    run = struct('dt', [], 'ntst', [], 't', [] ...  
                  ); 
              
    constants = struct('g', [] ...
                  );              
          
    flow = struct('h', [], ...
                  'hu', [], 'hv', [], ...
                  'zb', [], 'kst', [] ... 
                  );
              
    bconds = struct('bwest', [], ...
                    'beast', [], ...
                    'bnorth', [], ...
                    'bsouth', [] ...
                  );               
end