function [parm, flow] =  build_structs()

    % defining structures that contain basic parameters and flow properties

    parm = struct('flowtype', [], ...
                  'nu', [], ...
                  'm', [], 'n', [], ...
                  'dx',[], 'dy', [], 'dt', [], ...
                  'ntst', [], ...
                  'xl', [], 'yl', [], ...
                  'ip', [], 'jp', [], 'im', [], 'jm', [] ... 
                  );
          
    flow = struct('u', [], ...
                  'transporting_u', [], 'transporting_v', [], ...
                  'rhsu', []  ...
                  );
              
end